[package]
name = "forge-game-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
combine = "4.6"
serde = { version = "1.0", features = ["derive"] }
serde_test = "1.0"
thiserror = "1.0"
